canopyConfig = {'isOrdered': False,
                'name': 'CANOPY',
                'partitionInputKind': [],
                'orderByColumn': '',
                'partitionAttributes': '',
                'unaliased_inputs': {'count': 0.0,
                                     'values': [],
                                     'desc': {}},
                'arguments': [{'datatype': 'DRIVER',
                               'isRequired': False,
                               'allowsLists': False,
                               'name': 'DOMAIN',
                               'value': ''},
                              {'datatype': 'DRIVER',
                               'isRequired': False,
                               'allowsLists': False,
                               'name': 'DATABASE',
                               'value': ''},
                              {'datatype': 'DRIVER',
                               'isRequired': False,
                               'allowsLists': False,
                               'name': 'USERID',
                               'value': ''},
                              {'datatype': 'DRIVER',
                               'isRequired': False,
                               'allowsLists': False,
                               'name': 'PASSWORD',
                               'value': ''},
                              {'datatype': 'DRIVER',
                               'isRequired': False,
                               'allowsLists': False,
                               'name': 'SSLSETTINGS',
                               'value': ''},
                              {'datatype': 'DRIVER',
                               'isRequired': False,
                               'allowsLists': False,
                               'name': 'SSLTRUSTSTOREPASSWORD',
                               'value': ''},
                              {'datatype': 'TABLE_NAME',
                               'isRequired': True,
                               'allowsLists': False,
                               'name': 'INPUTTABLE',
                               'value': 'computers_train1_public'},
                              {'datatype': 'DOUBLE',
                               'isRequired': True,
                               'allowsLists': False,
                               'name': 'LOOSEDISTANCE',
                               'value': '1000'},
                              {'datatype': 'DOUBLE',
                               'isRequired': True,
                               'allowsLists': False,
                               'name': 'TIGHTDISTANCE',
                               'value': '500'}],
                'required_input': [],
                'hasInputTable': False,
                'asterarguments': [{'name': 'schema',
                                    'value': '',
                                    'label': 'Schema'},
                                   {'name': 'outputType',
                                    'value': '',
                                    'label': 'Output Table Type'},
                                   {'name': 'hashKey',
                                    'value': '',
                                    'label': 'Hash Key Column'}]}
