'''
Created on May 15, 2017

@author: dt186022
'''
textTokenizerConfig = {"orderByColumn":"",
                       "partitionAttributes":"",
                       "unaliased_inputs":{"count":1,"values":["text_chunked"],"desc":{}},
                       "name":"TEXTTOKENIZER",
                       "partitionInputKind":["PartitionByAny","Dimension"],
                       "hasInputTable":True,
                       "asterarguments":[
                           {"name":"schema", "value":"", "label":"Schema"},
                           {"name":"outputType","value":"","label":"Output Table Type"},
                           {"name":"hashKey","value":"","label":"Hash Key Column"}],
                       "required_input":[
                           {"kind":"Dimension","name":"dict","isOrdered":False,"value":"","orderByColumn":"","isRequired":False,"partitionAttributes":""}],
                       "isOrdered":False,
                       "arguments":[
                           {"datatype":"STRING",
                            "isRequired":False,
                            "allowsLists":False,
                            "name":"LANGUAGE",
                            "value":""},
                           {"datatype":"COLUMNS",
                            "isRequired":True,
                            "allowsLists":False,
                            "name":"TEXTCOLUMN",
                            "value":"chunk"},
                           {"datatype":"STRING",
                            "isRequired":False,
                            "allowsLists":False,
                            "name":"OUTPUTDELIMITER",
                            "value":""},
                           {"datatype":"BOOLEAN",
                            "isRequired":False,
                            "allowsLists":False,
                            "name":"OUTPUTBYWORD",
                            "value":""},
                           {"datatype":"STRING",
                            "isRequired":False,
                            "allowsLists":False,
                            "name":"USERDICTIONARYFILE",
                            "value":""},
                           {"datatype":"STRING",
                            "isRequired":False,
                            "allowsLists":False,
                            "name":"MODEL",
                            "value":""},
                           {"datatype":"COLUMNS",
                            "isRequired":False,
                            "allowsLists":True,
                            "name":"ACCUMULATE",
                            "value":""}
                        ]}

nertrainerConfig = {'isOrdered': False,
                    'name':'NERTRAINER',
                    'partitionInputKind': ['PartitionByKey'],
                    'orderByColumn': '',
                    'partitionAttributes': ['id'],
                    'unaliased_inputs': {'count': 1.0, 'values': ['ner_sports_train'], 'desc': {}},
                    'arguments': [
                        {'datatype': 'DRIVER', 'isRequired': False, 'allowsLists': False, 'name': 'DOMAIN', 'value': ''},
                        {'datatype': 'DRIVER', 'isRequired': False, 'allowsLists': False, 'name': 'DATABASE', 'value': ''},
                        {'datatype': 'DRIVER', 'isRequired': False, 'allowsLists': False, 'name': 'USERID', 'value': ''},
                        {'datatype': 'DRIVER', 'isRequired': False, 'allowsLists': False, 'name': 'PASSWORD', 'value': ''},
                        {'datatype': 'DRIVER', 'isRequired': False, 'allowsLists': False, 'name': 'SSLSETTINGS', 'value': ''},
                        {'datatype': 'DRIVER', 'isRequired': False, 'allowsLists': False, 'name': 'SSLTRUSTSTOREPASSWORD', 'value': ''},
                        {'datatype': 'COLUMNS', 'isRequired': True, 'allowsLists': False, 'name': 'TEXTCOLUMN', 'value': 'content'},
                        {'datatype': 'STRING', 'isRequired': False, 'allowsLists': False, 'name': 'LANGUAGE', 'value': ''},
                        {'datatype': 'STRING', 'isRequired': True, 'allowsLists': False, 'name': 'MODELFILE', 'value': 'ner_model.bin'},
                        {'datatype': 'DOUBLE', 'isRequired': False, 'allowsLists': False, 'name': 'ETA', 'value': ''},
                        {'datatype': 'INTEGER', 'isRequired': False, 'allowsLists': False, 'name': 'MAXITERATION', 'value': ''},
                        {'datatype': 'INTEGER', 'isRequired': False, 'allowsLists': False, 'name': 'MINFEATUREOCCURNUM', 'value': ''},
                        {'datatype': 'STRING', 'isRequired': True, 'allowsLists': False, 'name': 'FEATURETEMPLATE', 'value': 'template_1.txt'},
                        {'datatype': 'STRING', 'isRequired': False, 'allowsLists': False, 'name': 'EXTRACTORJAR', 'value': ''}],
                    'required_input': [],
                    'hasInputTable': True,
                    'asterarguments': [
                        {'name': 'schema', 'value': '', 'label': 'Schema'}, {'name': 'outputType', 'value': '', 'label': 'Output Table Type'}, {'name': 'hashKey', 'value': '', 'label': 'Hash Key Column'}
                        ]}

nerConfig = {'isOrdered': False,
             'name': 'NER',
             'partitionInputKind': ['PartitionByAny'],
             'orderByColumn': '',
             'partitionAttributes': '',
             'unaliased_inputs': {'count': 1.0,
                                  'values': ['ner_sports_test'],
                                  'desc': {}},
             'arguments': [{'datatype': 'COLUMNS', 'isRequired': True, 'allowsLists': False, 'name': 'TEXTCOLUMN', 'value': 'content'},
                           {'datatype': 'STRING', 'isRequired': False, 'allowsLists': False, 'name': 'LANGUAGE', 'value': ''},
                           {'datatype': 'STRING', 'isRequired': False, 'allowsLists': True, 'name': 'MODELS', 'value': 'ner_model.bin'},
                           {'datatype': 'COLUMNS', 'isRequired': False, 'allowsLists': True, 'name': 'ACCUMULATE', 'value': ['id']},
                           {'datatype': 'INTEGER', 'isRequired': False, 'allowsLists': False, 'name': 'SHOWCONTEXT', 'value': '2'}],
             'required_input': [{'kind': 'Dimension', 'name': 'rules', 'isOrdered': False, 'value': 'rule_table', 'orderByColumn': '', 'isRequired': False, 'partitionAttributes': ''},
                                {'kind': 'Dimension', 'name': 'dict', 'isOrdered': False, 'value': '', 'orderByColumn': '', 'isRequired': False, 'partitionAttributes': ''}],
             'hasInputTable': True,
             'asterarguments': [{'name':'schema', 'value': '', 'label': 'Schema'},
                                {'name': 'outputType', 'value': '', 'label': 'Output Table Type'},
                                {'name': 'hashKey', 'value': '', 'label': 'Hash Key Column'}]}

nerEvaluatorConfig = {'isOrdered': False,
                      'name': 'NEREVALUATOR',
                      'partitionInputKind': ['PartitionByKey'],
                      'orderByColumn': '',
                      'partitionAttributes': ['id'],
                      'unaliased_inputs': {'count': 1.0, 'values': ['ner_sports_test'], 'desc': {}},
                      'arguments': [
                          {'datatype': 'COLUMNS',
                           'isRequired': True,
                           'allowsLists': False,
                           'name': 'TEXTCOLUMN',
                           'value': 'content'},
                          {'datatype': 'STRING', 'isRequired': False, 'allowsLists': False, 'name': 'LANGUAGE', 'value': ''},
                          {'datatype': 'STRING', 'isRequired': True, 'allowsLists': False, 'name': 'MODEL', 'value': 'ner_model.bin'}],
                      'required_input': [],
                      'hasInputTable': True,
                      'asterarguments': [{'name': 'schema', 'value': '', 'label': 'Schema'},
                                         {'name': 'outputType', 'value': '', 'label': 'Output Table Type'},
                                         {'name': 'hashKey', 'value': '', 'label': 'Hash Key Column'}]}
